app/__init__.py
import os

from flask import Flask
from .gallery.probability import prob_pee_sea
from .gallery.quadratic import quad_pizza
from . import routes
from . import gallery


# def create_app(test_config=None):
app = Flask(__name__)  # , instance_relative_config=True)
app.config.from_mapping(
    SECRET_KEY='dev')

# if test_config is None:
#     # load the instance config, if it exists, when not testing
#     app.config.from_pyfile('config.py', silent=True)
# else:
#     # load the test config if passed in
#     app.config.from_mapping(test_config)

# ensure the instance folder exists
try:
    os.makedirs(app.instance_path)
except OSError:
    pass

# # root
app.register_blueprint(routes.bp_home)
app.add_url_rule('/', endpoint='home')

app.register_blueprint(routes.bp_contact)
app.add_url_rule('/contact', endpoint='contact')

app.register_blueprint(routes.bp_todo)
app.add_url_rule('/not-implemented', endpoint='not-implemented')

# gallery
app.register_blueprint(gallery.bp_gal)

app.register_blueprint(gallery.bp_demo)

# dash plotly apps
app = prob_pee_sea(app)
app = quad_pizza(app)

if __name__ == "__main__":
    app.run()

app/db/__init__.py
import json
import random
from collections import defaultdict as ddc

from flask import current_app
from werkzeug.exceptions import abort


def read_json(path):
    '''instead of sqlite I store data simply in json file'''
    with open(path) as f:
        return json.load(f)


def get_demo(id: str):
    '''read dict related to one specific demo'''
    if id == 'random':
        content = read_json(current_app.root_path
                            + '/data/db.json')
        name = random.choice(list(content.keys()))
        # this might link to the same tutorial again.
        demo = content[name]
    else:
        demo = read_json(current_app.root_path
                         + '/data/db.json')[id]

    if demo is None:
        abort(404, 'Demo does not exist.')
    return demo


def get_tags():
    '''
    count tag occurances
    create list of strings (tag #occurances)
    TODO: Once I have many, I have to pick some
     subset of those
    '''
    # tags for math, python and topic separated
    dm, dp, dt = ddc(lambda: 0), ddc(lambda: 0), ddc(lambda: 0)
    all = set()
    content = read_json(current_app.root_path
                        + '/data/db.json')

    # counting tag occurances for math/python/main topics
    for _, value in content.items():
        for tag in value['tags_math']:
            dm[tag] += 1
            all.add(tag)
        for tag in value['tags_python']:
            dp[tag] += 1
            all.add(tag)
        for tag in value['tags_topic']:
            dt[tag] += 1
            all.add(tag)

    # creating string, tag name + #occurances
    lm = [key + ': ' + str(value) + 'x' for key, value in dm.items()]
    lp = [key + ': ' + str(value) + 'x' for key, value in dp.items()]
    lt = [key + ': ' + str(value) + 'x' for key, value in dt.items()]
    return (lm, lp, lt, all)


def get_demos_by_tag(tag: str):
    '''search all demos containng particular tag
    '''
    demos_tagged = {}
    content = read_json(current_app.root_path+'/data/db.json')

    for key, value in content.items():
        if tag in value['tags_math']:
            demos_tagged[key] = value
        elif tag in value['tags_python']:
            demos_tagged[key] = value
        elif tag in value['tags_topic']:
            demos_tagged[key] = value
        else:
            # TODO, handle error
            pass
    return demos_tagged

app/gallery/__init__.py
from flask import (
    Blueprint, render_template, current_app
)

import db
from .fft import fft_intro              # noqa
from .sets import sets_intro            # noqa
from .probability import prob_pee_sea   # noqa
from .quadratic import quad_pizza       # noqa
from .fft_compression import compress_fourier   # noqa
from .newton_disc import nd   # noqa


bp_gal = Blueprint('gallery', __name__, url_prefix='/gallery')
bp_demo = Blueprint('demo', __name__, url_prefix='/demo')


@bp_gal.route('/')
@bp_gal.route('/<string:include_tags>', methods=['GET'])
def index(include_tags='all'):
    '''rfenders Gallery index page with all
    TODO: paging for the case of many demos
    '''
    if include_tags == 'all':
        content = db.read_json(current_app.root_path
                               + '/data/db.json')
    else:
        content = db.get_demos_by_tag(include_tags)

    return render_template(
            'gallery/index.html',
            demos=content,
            links=db.get_tags())


@bp_demo.route('/<string:id>', methods=['GET'])
def demo(id='random'):
    ''' Renders demo page based on the
    info from the json file.s
    '''
    demo = db.get_demo(id)
    if demo['type'] == 'dash':
        return render_template(
            'gallery/dash_item.html',
            demo=demo,
            dash_url=demo['url']
            )
    elif demo['type'] == 'plotly':
        plot = globals()[demo['pipe_name']]()
        return render_template(
            'gallery/item.html',
            demo=demo,
            plot=plot)
    else:
        return render_template(
            'gallery/todo.html',
            links=db.get_tags(),
            demo=demo)

app/main.py
import os
from flask import Flask
import routes
import gallery


app = Flask(__name__)
app.config.from_mapping(
    SECRET_KEY='dev')

# ensure the instance folder exists
try:
    os.makedirs(app.instance_path)
except OSError:
    pass

print(app.instance_path)

from gallery.probability import prob_pee_sea
from gallery.quadratic import quad_pizza
from gallery.fft_compression import compress_fourier
from gallery.newton_disc import nd
from gallery.spectrometer import spectrometer

# # root
app.register_blueprint(routes.bp_home)
app.add_url_rule('/', endpoint='home')

app.register_blueprint(routes.bp_contact)
app.add_url_rule('/contact', endpoint='contact')

app.register_blueprint(routes.bp_todo)
app.add_url_rule('/not-implemented', endpoint='not-implemented')

# gallery
app.register_blueprint(gallery.bp_gal)

app.register_blueprint(gallery.bp_demo)

# dash plotly apps
app = prob_pee_sea(app)
app = quad_pizza(app)
app = compress_fourier(app)
app = nd(app)
app = spectrometer(app)

if __name__ == "__main__":
    app.run()

app/routes/__init__.py
from flask import (
    Blueprint, render_template
)

# import app.db as db
import db

bp_home = Blueprint('home', __name__, url_prefix='/')
bp_contact = Blueprint('contact', __name__, url_prefix='/')
bp_todo = Blueprint('not-implemented', __name__)


@bp_home.route('/')
def home():
    return render_template(
        'home.html',
        links=db.get_tags())


@bp_contact.route('/contact')
def contact():
    return render_template(
        'contact.html',
        links=db.get_tags())


@bp_todo.route('/not-implemented')
def todo():
    return render_template(
        'todo.html',
        links=db.get_tags())

app/templates/base.html
<!doctype html>
<head>
  <title>{% block title %}{% endblock %} Pymarad</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async
          src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
  </script>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>
  <section class="page-area">
    <header class="header-area">
      <div class="header-area--inner header-area--head">
        <h1 class="header-area--logo">
          <a href="{{ url_for('home') }}">
            Pymarad
          </a>
        </h1>
      </div>
      {% block nav %}
      <nav class="header-area--nav">
        <ul class="header-area--nav--list">
        <li>
            <a href="{{ url_for('gallery.index') }}">
            Gallery
            </a>
        </li>
        <li>
            <a href="{{ url_for('demo.demo', id='random') }}">
                Random demo
            </a>
        </li>
        <li>
            <a href="{{ url_for('contact') }}">
            Contact
            </a>
        </li>
        </ul>
      </nav>
      {% endblock %}
    </header>
    
    {% block logo %}{% endblock %}

    <div class="grid-container">
      {% block sidebar %}
        <div class="sidebar">
          <h4>
            {% block tags3 %} Main Topics {% endblock %}
          </h4>
          {% for link in links[2] %}
            <a href="{{ url_for('gallery.index', include_tags=link.split(':')[0]) }}">
              {{ link }}
            </a>
          {% endfor %}

          <h4>
            {% block tags1 %} Math Topics {% endblock %}
          </h4>
          {% for link in links[0] %}
            <a href="{{ url_for('gallery.index', include_tags=link.split(':')[0]) }}">
              {{ link }}
            </a>
          {% endfor %}

          <h4>
          {% block tags2 %} Python Topics {% endblock %}
          </h4>
          {% for link in links[1] %}
            <a href="{{ url_for('gallery.index', include_tags=link.split(':')[0]) }}">
              {{ link }}
            </a>
          {% endfor %}
        </div>
      {% endblock %}

      {% block content %}{% endblock %}
    </div>

    {% block footer %}
      <footer class="footer-area">
        <ul>
          <li>
            <address>Author:
              <a class='text' href="mailto:ddthumb@gmail.com">
                David Paleček
              </a>
            </address>
          </li>
          <li>
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg"
                  width="20px"
                  alt="Flask" />
            <a class="text" href="https://flask.palletsprojects.com/en/2.1.x/" target="_blank">
              Flask (v 2.1.2)
            </a>
          </li>
          <li>
            <img src="../static/fig/GitHub-Mark-Light-64px.png" width='15px'
                alt='github-icon'/>
            <a class="text" href="http://github.com/palec87/pymarad" target="_blank">
              Pymarad
            </a>
          </li>
          <li>
            <img src="../static/fig/GitHub-Mark-Light-64px.png" width='15px'
                  alt="github-icon"/>
            <a class="text" href="http://github.com/palec87/pymapp" target="_blank">
              Pyma-app
            </a>
          </li>
        </ul>
      </footer>
    {% endblock %}
  </section>
</body>

app/templates/contact.html
{% extends 'base.html' %}

{% block content %}
  <section class="content">
    <ul class="text">
      <li>
        Do you have a project suggestion?
      
      Raise a feature suggest 
        <a class='text' 
            href="https://github.com/palec87/pymapp"
            target="_blank">
                here.
        </a>
      </li>
      <li>
        Wanna collaborate, send me an 
        <a class='text' href="mailto:ddthumb@gmail.com">
          email.
        </a>
      </li>
    </ul>
  </section>
{% endblock %}

app/templates/gallery/index.html
{% extends 'base.html' %}

{% block content %}
  <section class="content">
    {% for name,item in demos.items() %}
      <article class="gallery-area--demo">
        <div class="gallery-area--demo--header">
          <img src= "{{ url_for('static', filename=item['toc_figure']) }}" alt="{{ item['toc_figure'] }}" />
          <h1 class="demo--title">
            <a class="action" href="{{ url_for('demo.demo', id=name) }}"> {{ item['title'] }}</a>
          </h1>
          <div class="about">by {{ item['author'] }}, last update: {{ item['last_update'] }}</div>
        </div>
        <p class="demo-body">Tags: {{ ', '.join(item['tags_math']+
                                          item['tags_python']+
                                          item['tags_topic']) }}</p>
      </article>
      {% if not loop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  </section>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block logo %}
<div class="content-area">
  <section class="visual-area">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <div class="title--logo">
      <h1>
        Pymarad
      </h1>
    </div>
    <div class="typewriter" id="myTypewriter">
      <h1>
      </h1>
    </div>
  </section>
</div>
<script>
  var messages=["Python Programming","High school math","Real-world problems",
                'Interactive projects'];
  var lens = ['580px', '480px', '570px', '530px']
  var idx=0;
  document.getElementById("myTypewriter").addEventListener("webkitAnimationEnd", changeTxt);
  document.getElementById("myTypewriter").addEventListener("animationend", changeTxt);

  function changeTxt(e){
    _h1 = this.getElementsByTagName("h1")[0];
    _h1.style.webkitAnimation = 'none'; // set element animation to none
    setTimeout(function() { // you surely want a delay before the next message appears
      _h1.innerHTML=messages[idx];
      var speed =0.15*messages[idx].length; // adjust the speed (3.5 is the original speed, 20 is the original string length
      _h1.style.maxWidth = lens[idx];
      _h1.style.webkitAnimation = 'typing '+speed+'s steps(30, end), blink-caret .75s step-end infinite'; //  switch to the original set of animation      
      (idx===messages.length-1)?idx=0:idx++; // if you have displayed the last message from the array, go back to the first one, else go to next message
      }, 0);
  }
</script>
{% endblock %}

{% block sidebar %}
  <div class="sidebar-home">
    <h4>
      {% block tags3 %} Main Topics {% endblock %}
    </h4>
    {% for link in links[2] %}
      <a href="{{ url_for('gallery.index', include_tags=link.split(':')[0]) }}">
        {{ link }}
      </a>
    {% endfor %}

    <h4>
      {% block tags1 %} Math Topics {% endblock %}
    </h4>
    {% for link in links[0] %}
      <a href="{{ url_for('gallery.index', include_tags=link.split(':')[0]) }}">
        {{ link }}
      </a>
    {% endfor %}

    <h4>
    {% block tags2 %} Python Topics {% endblock %}
    </h4>
    {% for link in links[1] %}
      <a href="{{ url_for('gallery.index', include_tags=link.split(':')[0]) }}">
        {{ link }}
      </a>
    {% endfor %}
  </div>
{% endblock %}

{% block content %}
  <section class="content-home">
    <ul class="text">
      <li>
        Pymarad combines high school math, real-world topics and
        programming in Python.
      </li>
      <li>
        Check out the 
        <a class="text"
          href="{{ url_for('gallery.index') }}">
          gallery
        </a>
        with the project demos, which tease you with
        some results of the projects themselves.
      </li>
      <li>
        Each project is also compiled into task and solution work sheets (links in demos).
      </li>
      <li>
        Work sheets open on the server, are interactive and well commented
        to guide you through some python coding experience.
      </li>
      <li>
        Btw. There is also a
        <a class="text"
          href="https://www.youtube.com/channel/UC9FRDaR5N5AzggJGQUaiCTQ"
          target="_blank">
            YouTube channel
        </a>  
        introducing each project task.
      </li>
    </ul>
  </section>
{% endblock %}